# Generated by Django 6.0.2 on 2026-03-16 04:07

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('cycle_type', models.CharField(choices=[('regular', 'Regular'), ('electric', 'Electric'), ('mountain', 'Mountain'), ('hybrid', 'Hybrid')], default='regular', max_length=20)),
                ('color', models.CharField(default='Black', max_length=50)),
                ('price_per_hour', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=6)),
                ('location', models.CharField(max_length=200)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('available_from', models.TimeField()),
                ('available_until', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cycles/')),
                ('rating', models.DecimalField(decimal_places=1, default=Decimal('4.5'), max_digits=3)),
                ('total_bookings', models.PositiveIntegerField(default=0)),
                ('registration_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_cycles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cycle',
                'verbose_name_plural': 'Cycles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', '-created_at'], name='cycles_cycl_owner_i_4c610b_idx'), models.Index(fields=['is_available', 'price_per_hour'], name='cycles_cycl_is_avai_b470d9_idx')],
            },
        ),
    ]
