# Generated by Django 6.0.2 on 2026-03-15 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_cycle_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cycle',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Cycle',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
